line-length = 120
indent-width = 4
target-version = "py311"
extend-exclude = ["dacite"]

[lint]
select = ["B", "C", "E", "F", "W", "I", "N", "Q", "UP", "RET", "RSE", "RUF", "ISC", "PLC", "PLE", "PLW", "T20", "PERF"]
ignore = [
# these come from ap's ruff file, but none are applicable to psedo rn
#    "B011",  # In AP, the use of assert False is essential because we optimise out these statements for release builds.
#    "C901",  # Author disagrees with limiting branch complexity
#    "N818",  # Author agrees with this rule, but Core AP violates this and changing it would be a hassle.
#    "PLC0415",  # In AP, we consider local imports totally fine & necessary
#    "PLC1802",  # Author agrees with this rule, but it literally changes the functionality of the code, which is unsafe.
#    "PLC1901",  # This is just not equivalent
#    "PLE1141",  # Gives false positives when the dict keys are tuples, but does not mention this in the suggested fix.
#    "UP015",  # Explicit is better than implicit, so we'd prefer to keep "r" in open() calls.


    "RUF012",  # annoying to manage all the mutable classvars required in ap
    "RET505",  # in no way is the visual distinction that they are exclusive elifs worse performance or something
#    "I001",  # import sorting, just annoying to see while fixing other things
]
